### ISSUE TITLE
[Android 9] Opening a special News article crahes app

### ISSUE THREAD

**Issue by Nokkfried** [postillonmedia/app#16]
If I open the recent article "Frau nach 48h aus begehbarem Kleiderschrank gerettet“ the Android App closes/crashes. Other articles can be opened and read without problems.
Huawei mate 10 Android 9.

**Comment by danielang** [comment]
Thank you for sharing this issue.
It seems to be an issue with the WebView-Implementation on Android 9.
Currently I am working on the notification feature... After that I'll take a look at this issue.

**Comment by danielang** [comment]
It looks like the hardware acceleration of the WebView implementation causes the problem.
If I disable it, the app runs without crashs on Android 9. Disabling the hardware acceleration leads to a slow performing WebView which is not capable to play videos or display animated content correctly.

**Comment by Nokkfried** [comment]
I took a look within the developer options, (see attached photo). Not sure if this the right parameter but hardware accelerations seems to be off?

Is there anything I can do to support your bug tracking?
Maybe send android bug report log?

Or is it possible that a certain access right to something is not set? 
Huawai is also very strict in regards of power savings and the battery optimizer is closing many apps.


![Screenshot_20190516_105117_com android settings](https://user-images.githubusercontent.com/29249605/57850031-33ad8b80-77dd-11e9-9b86-b02e65ac43f5.jpg)

**Comment by danielang** [comment]
Thank you for the reply. This has nothing to do with the developer settings of your device. Each app can be configured to use the hardware acceleration of the Android OS. This is done in the AndroidManifest.xml which describes the app. Take a look at [line 17 of the AndroidManifest](https://github.com/postillonmedia/app/blob/master/android/app/src/main/AndroidManifest.xml#L17)
If we disable this parameter and build the app; it will work without crashes on Android 9.

It is also possible to disable the acceleration only on the embedded webviews and let it on in the rest of the app: The app still works fine. So I think it has something to do with the webview implementation and their usage of the hardware acceleration on Android 9.

It would be great if you can send me some more details/bugreports. This would be very helpful.

If you like I could send you a builded app with disabled hardware acceleration, so you can validate my suspicion.

**Comment by danielang** [comment]
I've opened an issue on the webview repository: [#575](https://github.com/react-native-community/react-native-webview/issues/575)

**Comment by Nokkfried** [comment]
> It would be great if you can send me some more details/bugreports. This would be very helpful.
> 
> If you like I could send you a builded app with disabled hardware acceleration, so you can validate my suspicion.

Yes, please send, so I can have a try.
I'll send you the bug report in a private message, there's to much sensible data inside...

**Comment by Nokkfried** [comment]
The article about "Game of thrones Finale: Fans wütend über... " also crashes on Android 9. Huawei Mate 10 .
