### ISSUE TITLE
 Vorheriger und Nächster post

### ISSUE THREAD

**Issue by Mr-Pine** [postillonmedia/app#19]
Mir fehlt das Feature aus der alten Version, direkt den nächsten oder vorherigen Artikel aufrufen zu können

**Comment by danielang** [comment]
Hallo :slightly_smiling_face: 
Vielen Dank für die  Anregung. Wir haben diese Funktionalität bereits in Planung. Zum tracken dient der bereits erstellte Issue #14. Diesen wollen wir weiter verwenden. Zur besseren Übersicht werde ich diesen Issue schließen.
