### ISSUE TITLE
Exiting Article from search chrashes app

### ISSUE THREAD

**Issue by Mr-Pine** [postillonmedia/app#20]
On trying to get back after reading a searched article, the app crashes

**Comment by danielang** [comment]
Which Android version do you have?

Is it possible that this issue corresponds to issue #16?

**Comment by Mr-Pine** [comment]
Android 9 on an Android One Phone

Am 15.05.2019 23:52 schrieb Daniel Lang <notifications@github.com>:

Which Android version do you have?

**Comment by danielang** [comment]
Thank you for clarification.
It seems to be the same issue as we currently discuss in #16.

**Comment by danielang** [comment]
This issue will hopefully fixed with the next update.
