### ISSUE TITLE
[Android 9] Background in article list toll small

### ISSUE THREAD

**Issue by Mr-Pine** [postillonmedia/app#21]
Thema image of an article in the list is larger than the background (see attached image)
![Screenshot_20190609-175711](https://user-images.githubusercontent.com/50425705/59161506-bd522f80-8ae3-11e9-98a7-c0f895cef162.jpg)

**Comment by danielang** [comment]
Hi @DaKie206,
thank you for reporting this issue, but this is intended. It was an idea of the designer @einsebastian to make the app UI more dynamic.
